### ISSUE TITLE
flymake error and alsmost can't input anything

### ISSUE THREAD

**Issue by llj098** [emacs-lsp/lsp-java#115]
**Describe the bug**

Not Appear all the time.

The Error: 
```
LSP :: Connected to [jdtls:13003].
error in process filter: flymake-error: [Flymake] Unexpected report from disabled backend lsp--flymake-backend
error in process filter: [Flymake] Unexpected report from disabled backend lsp--flymake-backend=
....
```

When the error happens, I  can't almost type anything. I tried lsp-restart-workspace, disable flymake-mode.

Only I quit the emacs and restart emacs, it goes back to normal

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages and it is reproducible with the clean config(the config from the getting started page.

**To Reproduce**
appears one or two time in a day, not always

**Expected behavior**
{populate}

**Screenshots**

**Logs**
in `lsp-log` buffer:

```
Mar 28, 2019 5:54:56 PM 3 problems reported for /TelegramService.java
Validate documents - 100% (done)
Mar 28, 2019 5:54:56 PM An internal error occurred during: "Validate documents".
null
java.lang.NullPointerException
        at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.performValidation(DocumentLifeCycleHandler.java:146)
        at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler.access$0(DocumentLifeCycleHandler.java:121)
        at org.eclipse.jdt.ls.core.internal.handlers.DocumentLifeCycleHandler$1.runInWorkspace(DocumentLifeCycleHandler.java:89)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

**Comment by yyoncho** [comment]
Can you check whether you can reproduce the issue with the latest lsp-java?

**Comment by yyoncho** [comment]
Closing based on inactivity.

**Comment by andrelkin** [comment]
I am having a similar symptoms. Maybe C-x 4 c indirect buffer has something to do with it.
