### ISSUE TITLE
Cannot install server

### ISSUE THREAD

**Issue by liushihao456** [emacs-lsp/lsp-java#124]
**Describe the bug**
Hi, I am new to using emacs to do Java developing. I followed your instructions, and everything works fine except that I don't seem to be able to install the server. The stacktrace says 
```
java.util.zip.ZipException: zip END header not found
```

I have openJDK 11 installed via Homebrew (brew cask install java11). Is it a problem with my JDK installation or something else?

**Logs**
```
--2019-04-17 20:09:56--  https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.4.0/maven-wrapper-0.4.0.jar
正在解析主机 repo.maven.apache.org (repo.maven.apache.org)... 151.101.24.215
正在连接 repo.maven.apache.org (repo.maven.apache.org)|151.101.24.215|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：48336 (47K) [application/java-archive]
正在保存至: “/var/folders/hc/3_n3f2fx03b198m2g1gf844h0000gn/T/lsp-java-install/.mvn/wrapper/maven-wrapper.jar”

     0K .......... .......... .......... .......... .......   100% 76.8K=0.6s

2019-04-17 20:09:58 (76.8 KB/s) - 已保存 “/var/folders/hc/3_n3f2fx03b198m2g1gf844h0000gn/T/lsp-java-install/.mvn/wrapper/maven-wrapper.jar” [48336/48336])

Exception in thread "main" java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1529)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1430)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1437)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1268)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1231)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:726)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:843)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:246)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:176)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:190)
	at org.apache.maven.wrapper.Installer.unzip(Installer.java:161)
	at org.apache.maven.wrapper.Installer.createDist(Installer.java:78)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:121)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)
```

**Comment by yyoncho** [comment]
Sounds like some tooling problem related to your java/maven/network proxy version. At the beginning of this buffer, there is a print statement starting with "Running ...". You could try to run that command outside of emacs and eventually check whether each of the files is downloaded correctly.

**Comment by liushihao456** [comment]
Thanks for the timely reply! :) I tried running that command manually, as you suggested, and it turned out that the command need to be run with ``sudo'', or it will report error like I posted. I am not very sure why this happens... In case you need the information, I am on macOS Mojave.

**Comment by yyoncho** [comment]
@liushihao456 this sounds like something specific for your setup so I will close the issue since it has a workaround.
