### ISSUE TITLE
ubuntu use lsp-java problems 

### ISSUE THREAD

**Issue by yuandaxing** [emacs-lsp/lsp-java#134]
Hi 
 os version : Ubuntu 16.04.3 LTS 
 emacs version: GNU Emacs 26.2 
 below is the error message when i install openjdk 8
May 19, 2019 11:11:46 AM Unexpected internal error
module-info.class [in <default> [in <module:jdk.unsupported>]] does not exist
Java Model Exception: Java Model Status [module-info.class [in <default> [in <module:jdk.unsupported>]] does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:573)
	at org.eclipse.jdt.internal.core.ModularClassFile.getModule(ModularClassFile.java:300)
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getSourceModuleDescription(PackageFragmentRoot.java:914)
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getModuleDescription(PackageFragmentRoot.java:890)
	at org.eclipse.jdt.internal.core.JarPackageFragmentRoot.getModuleDescription(JarPackageFragmentRoot.java:321)
	at org.eclipse.jdt.internal.core.JrtPackageFragmentRoot.getModule(JrtPackageFragmentRoot.java:144)
	at org.eclipse.jdt.internal.core.JavaProject.lambda$6(JavaProject.java:793)
	at org.eclipse.jdt.internal.core.JavaProject.internalDefaultRootModules(JavaProject.java:815)
	at org.eclipse.jdt.internal.core.JavaProject.defaultRootModules(JavaProject.java:791)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:738)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:1046)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:991)
	at org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots(JavaProject.java:968)
	at org.eclipse.jdt.internal.core.JavaProject.buildStructure(JavaProject.java:482)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:268)
May 19, 2019 11:17:46 AM Error computing hover
Index out of bounds
Java Model Exception: Java Model Status [Index out of bounds]
	at org.eclipse.jdt.internal.core.Openable.codeSelect(Openable.java:163)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:390)
	at org.eclipse.jdt.internal.core.CompilationUnit.codeSelect(CompilationUnit.java:383)
	at org.eclipse.jdt.ls.core.internal.JDTUtils.findElementsAtSelection(JDTUtils.java:616)
	at org.eclipse.jdt.ls.core.internal.HoverInfoProvider.computeHover(HoverInfoProvider.java:84)
	at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.computeHover(HoverHandler.java:50)
	at org.eclipse.jdt.ls.core.internal.handlers.HoverHandler.hover(HoverHandler.java:39)

when i use openjdk-9 headless, the error message is changed.

**Comment by yyoncho** [comment]
can you try to delete the workspace (by default it is located in `~/.emacs.d/workspace` and retry?.

**Comment by yuandaxing** [comment]
@yyoncho thank you very much, it works.
