### ISSUE TITLE
There was an exception when starting the jdt language server.

### ISSUE THREAD

**Issue by Cuishibing** [emacs-lsp/lsp-java#139]
**Describe the bug**
There was an exception `java.lang.NumberFormatException: For input string: ""` when starting the jdt server.

**To Reproduce**
* OS version is windows 10 HOME
* emacs version is emacs-26.1-x86_64
* I didn't use the auto install feature to install the jdt server for network reasons. I downloaded the archive using the download tool and extracted it to the ‘.emacs.d\eclipse.jdt.ls\server’ directory.

**Expected behavior**
The server can start normally

**Screenshots**
![捕获](https://user-images.githubusercontent.com/16128845/58742886-651f8b80-845a-11e9-842f-6c7445e4c184.PNG)

**Logs**
````
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.eclipse.osgi.storagemanager.StorageManager.updateTable(StorageManager.java:526)
	at org.eclipse.osgi.storagemanager.StorageManager.open(StorageManager.java:723)
	at org.eclipse.osgi.storage.Storage.getChildStorageManager(Storage.java:2108)
	at org.eclipse.osgi.storage.Storage.getInfoInputStream(Storage.java:2125)
	at org.eclipse.osgi.storage.Storage.<init>(Storage.java:240)
	at org.eclipse.osgi.storage.Storage.createStorage(Storage.java:175)
	at org.eclipse.osgi.internal.framework.EquinoxContainer.<init>(EquinoxContainer.java:72)
	at org.eclipse.osgi.launch.Equinox.<init>(Equinox.java:34)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:315)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)

Process jdtls stderr finished
````

**Comment by yyoncho** [comment]
Can you check the \*lsp-log\* ? It has the command that lsp-mode is running, can you copy it as try to run it outside of emacs?

**Comment by Cuishibing** [comment]
Thanks a lot, when I copy the command and run it outside of emacs, I get the same error log.The strange thing is: based on the same configuration can run well under win7, may be other reasons. thank you very much.Maybe I should use a Linux distribution, haha
