### ISSUE TITLE
m2e: could not update project configuration

### ISSUE THREAD

**Issue by GabCamarda** [emacs-lsp/lsp-java#167]
**Describe the bug**
When trying to import a multi-module maven project, it fails indicating that there is a problem updating the configuration of one of the modules. It doesn't seem related to lsp-java, but rather to eclipse and the m2e plugin. I've tried cleaning `.settings`, `.project` and `.classpath`, the workspace folder and `.lsp-session` and run various `mvn clean`; no luck.

**Note**
Latest release available from Elpa for lsp-mode and lsp-java. I also re-installed eclipse language server through lsp-java

**To Reproduce**
Import a multi-module maven project for the first time, select `i` to import root and let it index and import all maven projects

**Expected behavior**
It should import all modules and build the project

**Logs**
```
 53% Starting Java Language Server - Importing Maven project(s) /Users/user/my-project-module[Starting]
 82% Starting Java Language Server - Importing Maven project(s) project my-project-module[Starting]
 90% Starting Java Language Server - Configuring java project my-project-module Updating duplicate resource: '/my-project-module/target/classes'.[Starting\
 ]
 22 Oct 2019, 14:17:35 Initialization failed
 Could not update project my-project-module configuration
 org.eclipse.core.runtime.CoreException: Could not update project my-project-module configuration
         at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:126)
         at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:508)
         at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
         at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
         at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
         at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:501)
         at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.configureNewMavenProjects(ProjectConfigurationManager.java:288)
         at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:175)
         at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$1.call(ProjectConfigurationManager.java:1)
         at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:177)
         at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
         at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
         at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1374)
         at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:143)
         at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.importProjects(ProjectConfigurationManager.java:133)
         at org.eclipse.jdt.ls.core.internal.managers.MavenProjectImporter.importToWorkspace(MavenProjectImporter.java:196)
         at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:148)
         at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:138)
         at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:262)
         at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
         at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
 Caused by: java.lang.NullPointerException
         at org.jboss.tools.maven.apt.internal.utils.ProjectUtils.parseProcessorOptions(ProjectUtils.java:94)
         at org.jboss.tools.maven.apt.internal.compiler.MavenCompilerJdtAptDelegate.getAnnotationProcessorConfiguration(MavenCompilerJdtAptDelegate.java:146)
         at org.jboss.tools.maven.apt.internal.AbstractAptConfiguratorDelegate.configureClasspath(AbstractAptConfiguratorDelegate.java:251)
         at org.jboss.tools.maven.apt.internal.AbstractAptProjectConfigurator.configureRawClasspath(AbstractAptProjectConfigurator.java:165)
         at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.invokeJavaProjectConfigurators(AbstractJavaProjectConfigurator.java:208)
         at org.eclipse.m2e.jdt.internal.AbstractJavaProjectConfigurator.configure(AbstractJavaProjectConfigurator.java:164)
         at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
         ... 20 more

 Could not update project my-project-module configuration[Error]
```

**Comment by yyoncho** [comment]
Did you try to delete the workspace in ~/.emacs/workspace?

**Comment by GabCamarda** [comment]
Yes, this could be related: https://github.com/emacs-lsp/lsp-java/issues/100

**Comment by yyoncho** [comment]
> To Reproduce
Import a multi-module maven project for the first time, select i to import root and let it index and import all maven projects

These steps are not sufficient to reproduce the issue, can you provide minimal reproducer?

**Comment by GabCamarda** [comment]
> > To Reproduce
> > Import a multi-module maven project for the first time, select i to import root and let it index and import all maven projects
> 
> These steps are not sufficient to reproduce the issue, can you provide minimal reproducer?

Unfortunately this happens at startup when importing the project. As the project does not build correctly, it keeps retrying to import it at each emacs startup. But it still throws the same exception. Running `mvn clean install` works without issues and Intellij has no issues. I've tried to Google the issue but no solutions were found.
Not sure how else to reproduce it.

**Comment by GabCamarda** [comment]
is there a workspace cache somewhere? I've also tried to remove `/.m2/repository` but again same issue.

**Comment by yyoncho** [comment]
The cache is in ~/.emacs.d/workspace. Can you provide a sample project to reproduce the issue with?

**Comment by GabCamarda** [comment]
This happens on my work project, which I can't share for obvious reasons. I'll try and reproduce it with a separate project when I get home. 

Is there anything else perhaps that should be deleted? So far, I've tried:
- delete `.settings`, `.project` and `.classpath`
- delete `~/.emacs.d/workspace` and `~/.emacs.d/.lsp-session-v1`
- import individual modules root
- run `mvn eclipse:clean` & `mvn eclipse:eclipse`
- run `mvn clean install`

**Comment by yyoncho** [comment]
AFAIK no. My wild guess is that jdt has bumped the m2e components and they have a but/ reregression. You may try with the milestone build from jdtls -https://download.eclipse.org/jdtls/milestones/?d

**Comment by GabCamarda** [comment]
Thanks, I'll try that and report back.

**Comment by GabCamarda** [comment]
Tried with a few older version up until `jdt-language-server-0.41.0-201907261503.tar.gz` - no luck unfortunately.

**Comment by GabCamarda** [comment]
is there a way to disable the "update configuration" while keeping the importing?

**Comment by yyoncho** [comment]
You mean the message?

**Comment by GabCamarda** [comment]
Yeah, from what is visible from the logs, it looks like it's importing all the maven projects and then updating their configuration (possibly updating dependencies). I was wondering if there's a way to just let it import the projects without updating the configuration (which should solve my issue)

**Comment by yyoncho** [comment]
That is not possible, this is what jdtls does to make the completion possible.

**Comment by GabCamarda** [comment]
May be related to this: https://bugs.eclipse.org/bugs/show_bug.cgi?id=496130

**Comment by yyoncho** [comment]
That is possible, but it debugging the problems that are not in the elisp code are out of my reach since I am not very familiar with the jdt-ls codebase(it is very huge ftr). What you could try is to try to import the project in vscode. If it fails, you could report it directly in the jdtls repo. This is what I was going to do after you provide a reproducer.

**Comment by GabCamarda** [comment]
Yep, it happens on vscode as well, same error but on different module. I'll issue a bug in the jdtls repo. Thanks for your help.

**Comment by GabCamarda** [comment]
Closing as fixed upstream. Thanks for your help @yyoncho
