### ISSUE TITLE
freeze 10sec

### ISSUE THREAD

**Issue by spavlovich001** [emacs-lsp/lsp-java#197]
```
LSP :: Connected to [jdtls:26831 status:starting].
Loading /home/user/media/source_project/java_teacher/.locals.el (source)...done
Deactivated linum mode
Error processing message (file-error "Opening directory" "Permission denied" "/home/user/docker").
```

```
Init...[Starting]
Creating watch for /home/user
0% Starting Java Language Server[Starting]
23 февр. 2020 г., 6:27:40 >> initialized
30% Starting Java Language Server[Starting]
23 февр. 2020 г., 6:27:41 Initialization failed
Failed to scan /home/user
org.eclipse.core.runtime.CoreException: Failed to scan /home/user
        at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scan(BasicFileDetector.java:136)
        at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.applies(GradleProjectImporter.java:75)
        at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.getImporter(ProjectsManager.java:432)
        at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:153)
        at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:145)
        at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:267)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.nio.file.AccessDeniedException: /home/user/docker
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
        at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2760)
        at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scanDir(BasicFileDetector.java:170)
        at org.eclipse.jdt.ls.core.internal.managers.BasicFileDetector.scan(BasicFileDetector.java:134)
        ... 7 more

Failed to scan /home/user[Error]
23 февр. 2020 г., 6:27:41 >> initialization job finished
23 февр. 2020 г., 6:27:41 >> workspace/didChangeConfiguration
23 февр. 2020 г., 6:27:41 >> java/buildWorkspace (incremental)
23 февр. 2020 г., 6:27:41 >> New configuration: {java={dependency={packagePresentation=flat}, errors={incompleteClasspath={severity=warning}}, trace={server=off}, maven={downloadSources=false}, referencesCode
23 февр. 2020 г., 6:27:41 >> build jobs finished
23 февр. 2020 г., 6:27:41 >> registerFeature 'workspace/didChangeWatchedFiles'
23 февр. 2020 г., 6:27:41 >> registerFeature 'workspace/didChangeWatchedFiles'
Creating watch for /home/user/media/source_project/java_teacher
23 февр. 2020 г., 6:27:41 >> watchers registered
```

How to disable scan /home directory?

**Comment by yyoncho** [comment]
1. Start clean - you could do that by deleting ~/.emacs.d/.lsp-session-v1 file.
2. When you open a java file and you are asked to select root don't select your root folder but the project root folder.

**Comment by spavlovich001** [comment]
> 1. ~/.emacs.d/.lsp-session-v1

everything is fine, thank you
