### ISSUE TITLE
lsp complains it cannot download Gradle version information

### ISSUE THREAD

**Issue by deb75** [emacs-lsp/lsp-java#203]
Hello,

In lsp's logs, I noticed this error :
```
9 mars 2020 12:00:36 Could not load Gradle version information
Cannot download published Gradle versions.
org.gradle.api.UncheckedIOException: Cannot download published Gradle versions.

	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:165)

	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.tryToDownloadAndCacheVersions(PublishedGradleVersions.java:149)

	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.create(PublishedGradleVersions.java:109)

	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersionsWrapper$LoadVersionsJob.run(PublishedGradleVersionsWrapper.java:60)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: java.net.UnknownHostException: services.gradle.org

	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)

	at java.net.PlainSocketImpl.connect(Unknown Source)

	at java.net.SocksSocketImpl.connect(Unknown Source)

	at java.net.Socket.connect(Unknown Source)

	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)

	at sun.net.NetworkClient.doConnect(Unknown Source)

	at sun.net.www.http.HttpClient.openServer(Unknown Source)

	at sun.net.www.http.HttpClient.openServer(Unknown Source)

	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)

	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)

	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)

	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)

	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:162)

	... 4 more
```

I am not that surprised of such error because I am behind a firewall that prevents all programs but a few to connect to internet. But I can still download manually through a web browser, do you know how I could overcome this error ?

Regards

**Comment by yyoncho** [comment]
I suggest you to ask in JDT LS repo, I am not familiar with server internals.

**Comment by deb75** [comment]
Thanks for your quick answeer, I forwarded to them the issue.

Regards
