### ISSUE TITLE
[help request] maven commands

### ISSUE THREAD

**Issue by egh** [emacs-lsp/lsp-java#223]
Thank you so much for `lsp-java`. My experience developing in java + emacs has gotten 1000% better since I began using it. The work is amazing.

I have one issue which I can't seem to work out. Often I'll be in emacs, using dap to run my tests and develop. Everything is great! The problem comes when I try to run a `mvn` command in a terminal.

I use `mvn package cargo:run` to run my webapp to test something. However, this will fail on test, e.g.

```
org.apache.maven.surefire.util.SurefireReflectionException: java.lang.reflect.InvocationTargetException; nested exception is java.lang.reflect.InvocationTargetException: null
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ArrayStoreException: sun.reflect.annotation.TypeNotPresentExceptionProxy
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:724)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:531)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:355)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.createAnnotationData(Class.java:3526)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at org.apache.maven.surefire.common.junit4.JUnit4TestChecker.isValidJUnit4Test(JUnit4TestChecker.java:64)
	at org.apache.maven.surefire.common.junit4.JUnit4TestChecker.accept(JUnit4TestChecker.java:51)
	at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:97)
	at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:194)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:92)
	... 9 more

Results :
```

Note that this error is one of many I seem to encounter where maven and the lsp server seem to be stepping on each other's toes. If the build succeeds, it may be missing some class.

Is there any way to work around this? Recently I've been quitting emacs :( which isn't much of a solution.

Thanks again for any help you can provide!

**Comment by yyoncho** [comment]
This is caused by lsp-java-autobuild-enabled being set to t and happens also in eclipse. The workaround is to disable autobuild but IMO it leads to a poorer experience(IMO). I guess the other option is to turn-off temporarily the JDT LS server.

**Comment by egh** [comment]
I ran `lsp-workspace-shutdown` and that worked, thank you! I still needed to run `mvn clean` before I got a good build, but that works. it's too bad I can't run mvn builds from within the language server, but I guess that's a limitation of it.

**Comment by egh** [comment]
Thanks for your help!
