### ISSUE TITLE
jdtls quits immediately

### ISSUE THREAD

**Issue by 132ikl** [emacs-lsp/lsp-java#293]
**Describe the bug**
Upon entering `java-mode` jdtls immediately exists with message

`Server jdtls:{pid} status:starting exited with status exit. Do you want to restart it? (y or n)`

The only jdk/jre I have installed is `java-11-openjdk`.

Note: It actually _did_ work at first, but then after a restart it stopped working. I didn't change any config between then. I have also attempted to reinstall the server and I have deleted the workspace folder.

**To Reproduce**
Using `openjdk 11.0.8 2020-07-14`, install jdtls and then attempt to enter `java-mode`.

**Expected behavior**
jdtls doesn't quit

**Logs**
from echo area:
```
LSP :: Connected to [jdtls:571029 status:starting].
LSP :: jdtls has exited (exited abnormally with code 13)
```

**Comment by yyoncho** [comment]
try deleting lsp-java-workspace-dir

**Comment by 132ikl** [comment]
> try deleting lsp-java-workspace-dir

i already tried this and it did not work

**Comment by yyoncho** [comment]
what do you have in stderr buffer?

**Comment by 132ikl** [comment]
what do you mean by the stderr buffer? how do i access that buffer?

**Comment by yyoncho** [comment]
there is buffer `*<conection-id>:stderr*`

**Comment by yyoncho** [comment]
Can you try also deleting the installation and reinstalling it again?

**Comment by 132ikl** [comment]
it just says ```Process jdtls stderr finished``` in the stderr buffer

reinstall the lsp-java installation or just jdtls?

**Comment by 132ikl** [comment]
trying to run the lsp directly:
```
$ java -jar org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar
An error has occurred. See the log file
/home/steven/.emacs.d/.local/etc/lsp/eclipse.jdt.ls/configuration/1605543591578.log.```

$ cat /home/steven/.emacs.d/.local/etc/lsp/eclipse.jdt.ls/configuration/1605543591578.log
!SESSION 2020-11-16 11:19:51.494 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_265
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US

!ENTRY org.eclipse.osgi 4 0 2020-11-16 11:19:51.713
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1461)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1434)

```

**Comment by 132ikl** [comment]
```
$ cat config.ini  | grep org.eclipse.core.runtime --color=auto
osgi.bundles=reference\:file\:ch.qos.logback.classic_1.2.3.v20200428-2012.jar@4,reference\:file\:ch.qos.logback.core_1.2.3.v20200428-2012.jar@4,reference\:file\:ch.qos.logback.slf4j_1.2.3.v20200428-2012.jar@4,reference\:file\:com.google.gson_2.8.2.v20180104-1110.jar@4,reference\:file\:com.google.guava_27.1.0.v20190517-1946.jar@4,reference\:file\:com.ibm.icu_67.1.0.v20200706-1749.jar@4,reference\:file\:javax.inject_1.0.0.v20091030.jar@4,reference\:file\:javax.xml_1.3.4.v201005080400.jar@4,reference\:file\:org.apache.ant_1.10.8.v20200515-1239/@4,reference\:file\:org.apache.commons.lang3_3.1.0.v201403281430.jar@4,reference\:file\:org.apache.felix.scr_2.1.24.v20200924-1939.jar@2\:start,reference\:file\:org.apache.log4j_1.2.15.v201012070815.jar@4,reference\:file\:org.eclipse.ant.core_3.5.800.v20200608-1251.jar@4,reference\:file\:org.eclipse.buildship.core_3.1.5.v20200806-2157-s.jar@4,reference\:file\:org.eclipse.compare.core_3.6.900.v20200412-2017.jar@4,reference\:file\:org.eclipse.core.commands_3.9.800.v20200910-0548.jar@4,reference\:file\:org.eclipse.core.contenttype_3.7.800.v20200724-0804.jar@4,reference\:file\:org.eclipse.core.expressions_3.7.0.v20200720-1126.jar@4,reference\:file\:org.eclipse.core.filebuffers_3.6.1000.v20200409-1035.jar@4,reference\:file\:org.eclipse.core.filesystem_1.7.700.v20200110-1734.jar@4,reference\:file\:org.eclipse.core.jobs_3.10.1000.v20200909-1312.jar@4,reference\:file\:org.eclipse.core.net_1.3.1000.v20200715-0827.jar@4,reference\:file\:org.eclipse.core.net.linux.x86_64_1.2.400.v20190924-1023.jar@4,reference\:file\:org.eclipse.core.resources_3.13.900.v20200915-0813.jar@4,reference\:file\:org.eclipse.core.runtime_3.19.0.v20200724-1004.jar@4\:start,reference\:file\:org.eclipse.core.variables_3.4.800.v20200120-1101.jar@4,reference\:file\:org.eclipse.debug.core_3.17.0.v20200930-0515.jar@4,reference\:file\:org.eclipse.equinox.app_1.5.0.v20200717-0620.jar@4,reference\:file\:org.eclipse.equinox.common_3.14.0.v20200929-1802.jar@2\:start,reference\:file\:org.eclipse.equinox.frameworkadmin_2.1.400.v20191002-0702.jar@4,reference\:file\:org.eclipse.equinox.frameworkadmin.equinox_1.1.400.v20200319-1546.jar@4,reference\:file\:org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar@4,reference\:file\:org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.0.v20200915-1442/@4,reference\:file\:org.eclipse.equinox.preferences_3.8.0.v20200422-1833.jar@4,reference\:file\:org.eclipse.equinox.registry_3.10.0.v20200929-1802.jar@4,reference\:file\:org.eclipse.equinox.security_1.3.500.v20200114-1637.jar@4,reference\:file\:org.eclipse.equinox.security.linux.x86_64_1.1.400.v20200915-1125/@4,reference\:file\:org.eclipse.equinox.simpleconfigurator_1.3.600.v20200721-1308.jar@4,reference\:file\:org.eclipse.equinox.simpleconfigurator.manipulator_2.1.500.v20200211-1505.jar@4,reference\:file\:org.eclipse.jdt.apt.core_3.6.800.v20200916-0645.jar@4,reference\:file\:org.eclipse.jdt.apt.pluggable.core_1.2.500.v20200322-1447.jar@4,reference\:file\:org.eclipse.jdt.compiler.apt_1.3.1200.v20200916-0645.jar@4,reference\:file\:org.eclipse.jdt.compiler.tool_1.2.1100.v20200916-0645.jar@4,reference\:file\:org.eclipse.jdt.core_3.24.0.v20201005-1133.jar@4,reference\:file\:org.eclipse.jdt.core.manipulation_1.14.200.v20201005-2114.jar@4,reference\:file\:org.eclipse.jdt.debug_3.17.0.v20200922-0523/@4,reference\:file\:org.eclipse.jdt.junit.core_3.10.900.v20201003-1543.jar@4,reference\:file\:org.eclipse.jdt.junit.runtime_3.5.400.v20200918-0332.jar@4,reference\:file\:org.eclipse.jdt.launching_3.19.0.v20200922-1657.jar@4,reference\:file\:org.eclipse.jdt.ls.core_0.65.0.202011130851.jar@4\:start,reference\:file\:org.eclipse.lsp4j_0.9.0.v20200229-1009.jar@4,reference\:file\:org.eclipse.lsp4j.jsonrpc_0.9.0.v20200229-1009.jar@4,reference\:file\:org.eclipse.ltk.core.refactoring_3.11.200.v20200920-1222.jar@4,reference\:file\:org.eclipse.m2e.archetype.common_1.16.0.20200610-1735/@4,reference\:file\:org.eclipse.m2e.core_1.17.0.20200924-1339.jar@4,reference\:file\:org.eclipse.m2e.jdt_1.17.0.20200924-1339.jar@4,reference\:file\:org.eclipse.m2e.lifecyclemapping.defaults_1.17.0.20200924-1339.jar@4,reference\:file\:org.eclipse.m2e.logback.configuration_1.16.0.20200318-1040.jar@4\:start,reference\:file\:org.eclipse.m2e.maven.indexer_1.16.0.20200610-1735/@4,reference\:file\:org.eclipse.m2e.maven.runtime_1.16.0.20200610-1735/@4,reference\:file\:org.eclipse.m2e.maven.runtime.slf4j.simple_1.16.0.20200610-1735/@4,reference\:file\:org.eclipse.m2e.workspace.cli_0.3.1.jar@4,reference\:file\:org.eclipse.osgi.services_3.9.0.v20200511-1725.jar@4,reference\:file\:org.eclipse.osgi.util_3.5.300.v20190708-1141.jar@4,reference\:file\:org.eclipse.text_3.10.400.v20200925-0557.jar@4,reference\:file\:org.eclipse.xtend.lib_2.24.0.v20201012-0920.jar@4,reference\:file\:org.eclipse.xtend.lib.macro_2.24.0.v20201012-0920.jar@4,reference\:file\:org.eclipse.xtext.xbase.lib_2.24.0.v20201012-0920.jar@4,reference\:file\:org.gradle.toolingapi_6.3.0.v20200806-2157-s.jar@4,reference\:file\:org.hamcrest.core_1.3.0.v20180420-1519.jar@4,reference\:file\:org.jboss.tools.maven.apt.core_1.5.3.201911081053.jar@4,reference\:file\:org.junit_4.13.0.v20200204-1500.jar@4,reference\:file\:org.slf4j.api_1.7.30.v20200204-2150.jar@4
```

**Comment by yyoncho** [comment]
This is not the command to run the server, you can use `M-: (lsp-java--ls-command)` will return it.

**Comment by 132ikl** [comment]
the command is: `java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.protocol=true -Dlog.level=ALL -noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication -jar /home/steven/.emacs.d/.local/etc/lsp/eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_1.6.0.v20200915-1508.jar -configuration /home/steven/.emacs.d/.local/etc/lsp/eclipse.jdt.ls/config_linux -data /home/steven/.emacs.d/.local/etc/java-workspace`

Output is:
```
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
An error has occurred. See the log file
/home/steven/.emacs.d/.local/etc/lsp/eclipse.jdt.ls/config_linux/1605657122885.log.
```
1605657122885.log: https://fs.ikl.sh/selif/hk8n7r13.txt

**Comment by yyoncho** [comment]
>  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

Considering this most likely you are not running with java 11. What does `java -version` outputs?

**Comment by 132ikl** [comment]
I am utterly confused, somehow jdk 8 ended up back on my system. After setting default to java 11 again it works fine. I have no idea how that's possible because I was able to clearly reproduce the issue with only java 11 instead. Oh well, I'll reopen the issue if the issue comes back.
