### ISSUE TITLE
couldn't debug using latest JDK version - java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by rajcspsg** [emacs-lsp/lsp-java#298]
Hi,
I've openJDK java 15 installed in my system and when I'm trying to debug using it, I get the below error -

```
-*- mode: dap-server-log; default-directory: "~/Coding/Java/yt_improve_ur_prog_skills_nio/app/src/main/java/" -*-
Debug Adapter started at Mon Dec  7 09:17:10

java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=35339,quiet=y -cp $CLASSPATH_ARGS HttpClientDemo
Debugger failed to attach: handshake failed - connection prematurally closed
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: HttpClientDemo has been compiled by a more recent version of the Java Runtime (class file version 59.65535), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

Debug Adapter exited abnormally with code 1 at Mon Dec  7 09:17:11
```

How can I enable preview like vs [code](https://stackoverflow.com/questions/55447687/how-to-fix-java-lang-unsupportedclassversionerror-test-class-file-version-52-6)

**Comment by yyoncho** [comment]
The issue is that you are running the language server with java less than v11. You may do `M-x shell-command RET java -version` to find your version and then use lsp-java-java-path to point it out to the correct version. You might have to delete lsp-java-workspace-dir as well.
