### ISSUE TITLE
"Failed to load extension bundles" message in *lsp-log* buffer on clean install

### ISSUE THREAD

**Issue by lispmac** [emacs-lsp/lsp-java#299]
**Describe the bug**

A clean install of `lsp-java` contains errors in the `*lsp-log*` buffer.

Could this be why running `dap-java-run-test-method` fails with the following error?

```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
```

**To Reproduce**

1. Clear `.emacs.d` directory.
2. Create `.emacs.d` directory with `init.el` file inside it.
3. Paste [Quick start](https://github.com/emacs-lsp/lsp-java#quick-start) installation configuration code into `init.el`.
4. Start Emacs.
5. Open file in Java project.
6. Look at `*lsp-log*` buffer.

**Expected behavior**

`*lsp-log*` should not contain any errors and com.microsoft.java.test.runner.jar should be loaded correctly.

**Logs**

```
Dec. 17, 2020, 6:41:15 p.m. Main thread is waiting
Dec. 17, 2020, 6:41:15 p.m. >> initialize
Dec. 17, 2020, 6:41:15 p.m. Initializing Java Language Server 0.67.0.202012170459
Dec. 17, 2020, 6:41:15 p.m. Failed to load extension bundles 
Load bundle list
org.eclipse.core.runtime.CoreException: Load bundle list
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:169)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:77)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:230)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:123)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Contains: Failed to get bundleInfo for bundle from /Users/lispmac/.emacs.d/.cache/lsp/eclipse.jdt.ls/bundles/com.microsoft.java.test.runner.jar
```

**Comment by yyoncho** [comment]
Did you check the content of that jar? Also, did you try to delete and reinstall the server?

**Comment by lispmac** [comment]
The JAR is present (in `.emacs.d/.cache/lsp/eclipse.jdt.ls/bindles/`) and its contents look like the correct JAR.  There is a `pom.xml` file and it says that the version of the JAR is `0.24.1`.  I've tried deleting the `.emacs.d` directory and starting with a clean slate (i.e. reinstalling the server) and see the same error.

**Comment by tareefdev** [comment]
I have the same issue. My config was just working fine, then it stopped. I checked the log buffer and saw the same error message here:

````
Jan 5, 2021, 8:23:25 PM Failed to load extension bundles 
Load bundle list
org.eclipse.core.runtime.CoreException: Load bundle list
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:169)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:77)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:230)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:123)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Contains: Failed to get bundleInfo for bundle from /home/tareef/.emacs.d/.cache/lsp/eclipse.jdt.ls/bundles/com.microsoft.java.test.runner.jar
````
I tried to reinstall the server, but nothing changed. BTW, I didn't change anything from my config.

**Comment by yyoncho** [comment]
I didn't have the time, but we should test if it works with a newer Java Test extension.

**Comment by tareefdev** [comment]
Could you please give me some instructions to do so?

**Comment by yyoncho** [comment]
Download extension from here - https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test unzip it and replace the jars under `~/.emacs.d/.cache/lsp/....`

**Comment by tareefdev** [comment]
That works! Still, I got the same error message in the lsp_log buffer, besides those two ones too:
````
Jan 5, 2021, 9:39:00 PM An internal error occurred during: "Initialize workspace".
Path must include project and resource name: /unit07
java.lang.IllegalArgumentException: Path must include project and resource name: /unit07
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2122)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:336)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$2.run(JDTLanguageServer.java:302)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
````

````
Jan 5, 2021, 9:39:02 PM An internal error occurred during: "Register Watchers".
Path must include project and resource name: /unit07
java.lang.IllegalArgumentException: Path must include project and resource name: /unit07
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:66)
	at org.eclipse.core.internal.resources.Workspace.newResource(Workspace.java:2122)
	at org.eclipse.core.internal.resources.Container.getFolder(Container.java:205)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager.registerWatchers(StandardProjectsManager.java:336)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager$1.run(StandardProjectsManager.java:100)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
````

**Comment by yyoncho** [comment]
@tareefdev I would try to delete lsp-session-file and restart emacs. I believe that you have some odd workspace folder in it.

**Comment by tareefdev** [comment]
@yyoncho you are right, the additional two error messages are gone. Still, the original one remains. For me, that's not a big deal as log as the server works normally. Thanks for your helping.

**Comment by Kazimazi** [comment]
Does it break `lsp-java-lens-mode` too?

**Comment by yyoncho** [comment]
@Kazimazi yes

**Comment by ackerleytng** [comment]
Also getting this error. @yyoncho when you replace the jars, do you mean remove the entire `bundles/` directory? My `.emacs.d/.cache/lsp/eclipse.jdt.ls/bundles/` contains some jars, like `org.reactivestreams.reactive-streams.jar` that are not in the unzipped extension file.

I tried only replacing the similar files, but the error still comes up.

**Comment by yyoncho** [comment]
@ackerleytng I think that you should replace everything coming from the test extension that is present in the server install dir. I will try to fix that issue during the weekend.

**Comment by yyoncho** [comment]
FTR you may check https://github.com/emacs-lsp/lsp-java/blob/master/install/pom.xml - it describes what install is doing.
