### ISSUE TITLE
No LSP features working in particular project

### ISSUE THREAD

**Issue by eeshugerman** [emacs-lsp/lsp-java#322]
### Describe the bug
> **NOTE** :This isn't much of a bug report since I don't know how to reproduce, except perhaps by sharing the Java code I'm working on, which I can't do. I'm mostly just hoping for some pointers with debugging and to see if anyone else is running into an issue like this. I'd understand if this is closed in the interest of a tidy issue tracker.

There's a Java project I'm working on in which no LSP features are working. There's an error in `*lsp-log*` (below), but it also appears in another Java project in which LSP works fine, so I'm thinking it's unrelated. Otherwise, all the logs I know of look OK -- I can even see the events firing in `*lsp-log*`, eg `Apr 14, 2021, 2:57:16 PM >> document/documentHighlight`, but no highlighting actually happens in the Java buffer.

##### `*Messages*`:
```
LSP :: Restarting jdtls:88964
LSP :: jdtls has exited (killed: 9)
LSP :: Restarting LSP in buffer Bocrypt.java
using config for config_mac
LSP :: Connected to [jdtls:89387/starting].
Truncate long lines enabled
LSP :: jdtls:89387 initialized successfully in folders: (/Users/elliott.shugerman/devel/acme-presto)
```

##### `*jdtls*`:
[empty]

##### `*jdtls::stderr*`:
```
Process jdtls stderr finished
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.

Process jdtls stderr<1> finished

Process jdtls stderr finished
OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
```

`*lsp-log*` (for `lsp-restart-workspace`):
<details>

```
Apr 14, 2021, 3:20:17 PM >> shutdown
Found the following clients for /Users/elliott.shugerman/devel/acme-presto/src/main/java/io/trino/plugin/acme/masker/Bocrypt.java: (server-id jdtls, priority 0)
The following clients were selected based on priority: (server-id jdtls, priority 0)
Cleaning up watches for folder /Users/elliott.shugerman/devel/acme-presto. There is no workspace watching this folder...
Apr 14, 2021, 3:20:18 PM Main thread is waiting
Apr 14, 2021, 3:20:18 PM >> initialize
Apr 14, 2021, 3:20:18 PM Initializing Java Language Server 0.71.0.202104141151
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [vscode.java.test.search.codelens, vscode.java.test.search.items.all, vscode.java.test.search.location, vscode.java.test.search.items, vscode.java.test.get.testpath, vscode.java.test.junit.argument]
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [java.project.list, java.getPackageData, java.resolvePath]
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [vscode.java.checkProjectSettings, vscode.java.isOnClasspath, vscode.java.fetchUsageData, vscode.java.validateLaunchConfig, vscode.java.resolveClassFilters, vscode.java.resolveMainMethod, vscode.java.resolveClasspath, vscode.java.resolveBuildFiles, vscode.java.resolveMainClass, vscode.java.updateDebugSettings, vscode.java.resolveSourceUri, vscode.java.fetchPlatformSettings, vscode.java.buildWorkspace, vscode.java.startDebugSession, vscode.java.inferLaunchCommandLength, vscode.java.resolveElementAtSelection, vscode.java.resolveJavaExecutable]
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [sts.java.addClasspathListener, sts.java.removeClasspathListener]
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [sts.java.javadoc]
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [sts.java.type]
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [sts.java.javadocHoverLink]
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [sts.java.location]
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [sts.java.search.packages, sts.java.search.types]
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [sts.java.hierarchy.supertypes, sts.java.hierarchy.subtypes]
Apr 14, 2021, 3:20:18 PM Static Commands: []
Apr 14, 2021, 3:20:18 PM Non-Static Commands: [java.edit.organizeImports, java.project.refreshDiagnostics, java.project.import, java.navigate.openTypeHierarchy, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.provideSemanticTokens, java.project.resolveStackTraceLocation, java.project.getAll, java.project.isTestFile, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.project.getSemanticTokensLegend, java.edit.stringFormatting, java.project.getSettings, java.project.updateSourceAttachment, java.project.resolveSourceAttachment, java.project.addToSourcePath]
Creating watch for /Users/elliott.shugerman/devel/acme-presto
This server does not support foldingRangeProvider
Apr 14, 2021, 3:20:18 PM >> initialized
Init...[Starting]
0% Starting Java Language Server[Starting]
Apr 14, 2021, 3:20:19 PM Importing Maven project(s)
34% Starting Java Language Server - /Users/elliott.shugerman/devel/acme-presto[Starting]
100% Starting Java Language Server - Refreshing '/presto-acme'.[Starting]
Apr 14, 2021, 3:20:19 PM Workspace initialized in 684ms
Ready[Started]
100% Starting Java Language Server - Refreshing '/presto-acme'.[Starting]
Apr 14, 2021, 3:20:19 PM >> initialization job finished
Apr 14, 2021, 3:20:19 PM >> workspace/didChangeConfiguration
Apr 14, 2021, 3:20:19 PM >> New configuration: {java={codeGeneration={toString={limitElements=0.0, listArrayContents=true, skipNullValues=false, codeStyle=STRING_CONCATENATION, template=${object.className} [${member.name()}=${member.value}, ${otherMembers}]}, generateComments=false, useBlocks=false, hashCodeEquals={useInstanceof=false, useJava7Objects=false}}, format={onType={enabled=true}, comments={enabled=true}, enabled=true}, progressReports={enabled=true}, foldingRange={enabled=true}, completion={importOrder=[java, javax, com, org], favoriteStaticMembers=[org.junit.Assert.*, org.junit.Assume.*, org.junit.jupiter.api.Assertions.*, org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*, org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*, org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], guessMethodArguments=true, overwrite=true, enabled=true, filteredTypes=[java.awt.*, com.sun.*], maxResults=0.0}, maxConcurrentBuilds=1.0, autobuild={enabled=true}, selection={enabled=true}, import={exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**], maven={enabled=true}, gradle={enabled=true, wrapper={enabled=true}, offline={enabled=false}}}, saveActions={organizeImports=false}, implementationsCodeLens={enabled=false}, signatureHelp={enabled=true}, referencesCodeLens={enabled=false}, maven={downloadSources=false, updateSnapshots=false}, trace={server=off}, configuration={updateBuildConfiguration=automatic, checkProjectSettingsExclusions=true}, errors={incompleteClasspath={severity=warning}}, dependency={packagePresentation=flat}, project={importHint=true, importOnFirstTimeStartup=automatic, referencedLibraries=[lib/**/*.jar], resourceFilters=[node_modules, .metadata, archetype-resources, META-INF/maven]}, imports={gradle={wrapper={checksums=[]}}}, sources={organizeImports={staticStarThreshold=99.0, starThreshold=99.0}}, server={launchMode=Hybrid}, showBuildStatusOnStart={enabled=false}, selectionRange={enabled=true}}}
Apr 14, 2021, 3:20:19 PM >> document/didOpen
Apr 14, 2021, 3:20:20 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Missing parameter for pluginExecutionFilter. groupId, artifactId, versionRange and goals must be specificed, but found: groupId = 'ca.vanzyl.maven.plugins'
artifactId = 'provisio-maven-plugin'
versionRange = '1.0.7'
goals = '[]'
java.lang.IllegalArgumentException: Missing parameter for pluginExecutionFilter. groupId, artifactId, versionRange and goals must be specificed, but found: groupId = 'ca.vanzyl.maven.plugins'
artifactId = 'provisio-maven-plugin'
versionRange = '1.0.7'
goals = '[]'
	at org.eclipse.m2e.core.internal.lifecyclemapping.model.PluginExecutionFilter.checkAllFieldsSet(PluginExecutionFilter.java:320)
	at org.eclipse.m2e.core.internal.lifecyclemapping.model.PluginExecutionFilter.match(PluginExecutionFilter.java:331)
	at org.eclipse.m2e.core.internal.lifecyclemapping.SimpleMappingMetadataSource.getPluginExecutionMetadata(SimpleMappingMetadataSource.java:81)
	at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateEffectiveLifecycleMappingMetadata0(LifecycleMappingFactory.java:598)
	at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateEffectiveLifecycleMappingMetadata(LifecycleMappingFactory.java:534)
	at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateEffectiveLifecycleMappingMetadata(LifecycleMappingFactory.java:258)
	at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateLifecycleMapping(LifecycleMappingFactory.java:190)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.setupLifecycleMapping(ProjectRegistryManager.java:614)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refreshPhase2(ProjectRegistryManager.java:533)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$3(ProjectRegistryManager.java:514)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:512)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:364)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:315)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:151)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:89)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.clean(MavenBuilder.java:208)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:851)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:229)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:277)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:330)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:333)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:385)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:406)
	at org.eclipse.core.internal.resources.Workspace.buildInternal(Workspace.java:515)
	at org.eclipse.core.internal.resources.Workspace.build(Workspace.java:405)
	at org.eclipse.jdt.ls.core.internal.managers.StandardProjectsManager$2.runInWorkspace(StandardProjectsManager.java:272)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Apr 14, 2021, 3:20:20 PM Errors occurred during the build.
Apr 14, 2021, 3:20:20 PM >> document/documentHighlight
Apr 14, 2021, 3:20:20 PM Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
Missing parameter for pluginExecutionFilter. groupId, artifactId, versionRange and goals must be specificed, but found: groupId = 'ca.vanzyl.maven.plugins'
artifactId = 'provisio-maven-plugin'
versionRange = '1.0.7'
goals = '[]'
java.lang.IllegalArgumentException: Missing parameter for pluginExecutionFilter. groupId, artifactId, versionRange and goals must be specificed, but found: groupId = 'ca.vanzyl.maven.plugins'
artifactId = 'provisio-maven-plugin'
versionRange = '1.0.7'
goals = '[]'
	at org.eclipse.m2e.core.internal.lifecyclemapping.model.PluginExecutionFilter.checkAllFieldsSet(PluginExecutionFilter.java:320)
	at org.eclipse.m2e.core.internal.lifecyclemapping.model.PluginExecutionFilter.match(PluginExecutionFilter.java:331)
	at org.eclipse.m2e.core.internal.lifecyclemapping.SimpleMappingMetadataSource.getPluginExecutionMetadata(SimpleMappingMetadataSource.java:81)
	at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateEffectiveLifecycleMappingMetadata0(LifecycleMappingFactory.java:598)
	at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateEffectiveLifecycleMappingMetadata(LifecycleMappingFactory.java:534)
	at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateEffectiveLifecycleMappingMetadata(LifecycleMappingFactory.java:258)
	at org.eclipse.m2e.core.internal.lifecyclemapping.LifecycleMappingFactory.calculateLifecycleMapping(LifecycleMappingFactory.java:190)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.setupLifecycleMapping(ProjectRegistryManager.java:614)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refreshPhase2(ProjectRegistryManager.java:533)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$3(ProjectRegistryManager.java:514)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:512)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:364)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:315)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.getProjectFacade(MavenBuilder.java:151)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.lambda$0(MavenBuilder.java:89)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:179)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:153)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:101)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder$BuildMethod.execute(MavenBuilder.java:88)
	at org.eclipse.m2e.core.internal.builder.MavenBuilder.build(MavenBuilder.java:197)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:846)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:229)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:277)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:330)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:333)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:385)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:406)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Apr 14, 2021, 3:20:20 PM Errors occurred during the build.
Apr 14, 2021, 3:20:20 PM >> registerWatchers'
Apr 14, 2021, 3:20:20 PM >> build jobs finished
ServiceReady[ServiceReady]
Apr 14, 2021, 3:20:20 PM >> registerFeature 'workspace/didChangeWatchedFiles'
Apr 14, 2021, 3:20:20 PM >> registerWatchers'
Apr 14, 2021, 3:20:20 PM >> watchers registered
Apr 14, 2021, 3:21:39 PM >> document/codeAction
Apr 14, 2021, 3:21:42 PM >> document/codeAction
Apr 14, 2021, 3:21:42 PM >> document/codeAction
Apr 14, 2021, 3:21:42 PM >> document/documentHighlight
Apr 14, 2021, 3:21:45 PM >> document/codeAction
Apr 14, 2021, 3:22:28 PM >> document/codeAction
Apr 14, 2021, 3:22:29 PM >> document/codeAction
Apr 14, 2021, 3:22:29 PM >> document/codeAction
Apr 14, 2021, 3:22:29 PM >> document/documentHighlight

```

</details>

### More information
- MacOS
- Emacs 28 with native-comp
- Spacemacs
- Not a Java expert

Let me know if there's anything else I can provide. Any tips are greatly appreciated!

**Comment by eeshugerman** [comment]
Not sure what did it -- I've updated `lsp-mode` a number of times since last working on the project -- but this issue has gone away
