### ISSUE TITLE
Emacs company-mode doesn't work correctly

### ISSUE THREAD

**Issue by yuchunzhou** [emacs-lsp/lsp-java#449]
before i press Enter key
![图片](https://github.com/emacs-lsp/lsp-java/assets/109280366/0f04939c-1e77-467d-8a45-4573386dde20)
after i press Enter key
![图片](https://github.com/emacs-lsp/lsp-java/assets/109280366/c315ecc8-4665-46c5-a0c2-0fed32a7166a)

**Comment by yyoncho** [comment]
check with M-x lsp-start-plain

**Comment by yuchunzhou** [comment]
> check with M-x lsp-start-plain

![图片](https://github.com/emacs-lsp/lsp-java/assets/109280366/3c5699bc-68fb-4479-b224-f7aea7721fd8)

**Comment by yuchunzhou** [comment]
@yyoncho Above is the input screenshot

**Comment by yyoncho** [comment]
I don't see anything wrong with that screenshot...

**Comment by yuchunzhou** [comment]
this is the backtrace log

**Comment by yuchunzhou** [comment]
![图片](https://github.com/emacs-lsp/lsp-java/assets/109280366/bd951d35-3698-485c-bd34-ca8e13188530)
![图片](https://github.com/emacs-lsp/lsp-java/assets/109280366/b889c951-8895-4d17-a9db-b33d8c472aea)

**Comment by yuchunzhou** [comment]
@yyoncho i upload the screenshot

**Comment by yuchunzhou** [comment]
> Type 3 symbols

@yyoncho i upload the screenshot

**Comment by yuchunzhou** [comment]
@yyoncho Maybe it's the snippet completion's problem

**Comment by yuchunzhou** [comment]
@yyoncho Can you look at the backtrace log?

**Comment by dgutov** [comment]
Superficially, it looks like an error in the language server ("Internal error"). But it could be triggered by some particular behavior of lsp-mode.

**Comment by yuchunzhou** [comment]
> Superficially, it looks like an error in the language server ("Internal error"). But it could be triggered by some particular behavior of lsp-mode.

Just the snippet completion will raise the error, other item types' completion is ok

**Comment by marasenna** [comment]
I didn't have this issue until I tried the workaround from #447 yesterday at around 11 pm UTC+3. I don't know how is this possible, but after that, reverting changes back or even deleting `.emacs.d` didn't help me.

**\*lsp-log\***
```
Sep 5, 2023, 11:00:10 AM Cannot evaluate the template.
Cannot evaluate the template.
org.eclipse.jface.text.templates.TemplateException: Cannot evaluate the template.
	at org.eclipse.jdt.internal.corext.template.java.JavaContextCore.evaluate(JavaContextCore.java:142)
	at org.eclipse.jdt.ls.core.internal.contentassist.SnippetCompletionProposal.evaluateGenericTemplate(SnippetCompletionProposal.java:395)
	at org.eclipse.jdt.ls.core.internal.handlers.CompletionResolveHandler.resolve(CompletionResolveHandler.java:131)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.resolveCompletionItem(JDTLanguageServer.java:620)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**java -version**
```
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8+6-void-r1)
OpenJDK 64-Bit Server VM (build 17.0.8+6-void-r1, mixed mode, sharing)
```

**Comment by marasenna** [comment]
It looks like the problem was only with the jdtls that lsp-java uses by default.

**What worked for me**
1. Download [jdtls 1.26.0 milestone](https://download.eclipse.org/jdtls/milestones/1.26.0/) and extract it

**Comment by yuchunzhou** [comment]
> It looks like the problem was only with the jdtls that lsp-java uses by default.
> 
> **What worked for me**
> 
>     1. Download [jdtls 1.26.0 milestone](https://download.eclipse.org/jdtls/milestones/1.26.0/) and extract it
> 
>     2. `(setq lsp-java-server-install-dir "path/to/jdtls")`

Thank you @marasenna , it seems that `jdtls 1.26.0` has fixed this problem, i also tried this version, it's ok.
