### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor

### ISSUE THREAD

**Issue by skybert** [emacs-lsp/lsp-java#54]
Hi, 

sorry if I'm reporting this in the wrong project, but I expect this to have something to do with how `lsp-java` interprets my multi-module Java project. 

`foo-core` is a 3rd level Maven module in a project structure like this:
```
proj/foo/foo-core
```

The class it cannot find is defined in the module's POM and everything builds with `mvn` (of course).

Can you direct me in the right direction for solving this?

Cheers,

-Torstein

Error from: `~/.emacs.d/workspace/.metadata/.log`:

```
!ENTRY org.eclipse.core.resources 4 75 2018-09-18 09:00:51.086
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.jdt.core 4 75 2018-09-18 09:00:51.086
!MESSAGE Errors running builder 'Java Builder' on project 'foo-core'.
!STACK 0
java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor
        at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
        at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1248)
        at java.base/java.lang.System$2.findBootstrapClassOrNull(System.java:2123)
        at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(ClassLoaders.java:125)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:617)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:550)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadJava6FactoryClasses(AnnotationProcessorFactoryLoader.java:641)
        at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.loadFactories(AnnotationProcessorFactoryLoader.java:580)
        at org.eclipse.jdt.apt.core.internal.AnnotationProcessorFactoryLoader.getJava6FactoriesAndAttributesForProject(AnnotationProcessorFactoryLoader.java:458)
        at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:134)
        at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:940)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
        at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
        at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
        at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
        at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:262)
        at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:180)
        at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:798)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:219)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:262)
        at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:315)
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
        at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:318)
        at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:370)
        at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:391)
        at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:145)
        at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by yyoncho** [comment]
I would try to delete the workspace(`lsp-java-workspace-dir`) folder and reimport the projects and monitor the messages in *messages* buffer while the projects are being imported. If this does not help with resolving, the issue seems to be related to eclipse jdt ls project. I guess minimal project which reproduces the issue could help jdt team members to resolve the issue. As a side note, I am validating the `lsp-java` behavior with trying the same project in vscode.

**Comment by yyoncho** [comment]
@skybert  Did you get a chance to try it?

**Comment by skybert** [comment]
@yyoncho , I've tried (several times) to delete everything, `lsp-java-workspace-dir` included and try again. Sadly always with the same result. An Emacs colleague of mine doesn't have this problem and he's working on the same code, so I'm really puzzled about this.

The last month I've been working on a Python project, so I haven't had the context for investigate this further, sadly. 

Thanks for asking, though :-)

**Comment by yyoncho** [comment]
Ok, now lsp-java provides an option to inspect the classpath for the project so you may check it when you are back to the java development. Also, the issue might be caused by the jdt version/installation.

**Comment by skybert** [comment]
Thanks for the info @yyoncho, I'll be sure to revisit this when I'm back in Java land. 

Keep up the good work, by the way. We really need stellar Java support in Emacs. It's AFAIK the only language which is lagging behind compared to the "modern" IDEs.

**Comment by skybert** [comment]
I've now back in Java country and have had another go at this. I noticed I could get everything working using a different user on my system, so I tried a few things. What worked was removing all my installed elisp packages, i.e. removing `~/.emacs.d/elpa` and load Emacs  anew (using `use-package`'s `:ensure t`).

I'm now have a well functioning `lsp-java` and `dap-java` (remote debugging against Tomcat) setup on a large code base (~4800 Java files and 65 Maven modules). 

Yeah!

**Comment by yyoncho** [comment]
I am glad that you like it. There are several new features available in JDT LS, but lsp-mode.el restructuring is keeping me busy, I will try to implement them in lsp-java during the holiday.

**Comment by muhmud** [comment]
I also had this issue. Turned out to be because of my Lombok configuration for jdt ls. Removing the `-Xbootclasspath` argument and providing the full path to the lombok jar fixed it for me, as mentioned here: https://github.com/redhat-developer/vscode-java/issues/652#issuecomment-466906125
