### ISSUE TITLE
lsp-java-organize-imports error

### ISSUE THREAD

**Issue by llj098** [emacs-lsp/lsp-java#73]
Hello, When I run `lsp-java-organize-imports ` in a java buffer it causes an error, the error message is below:

```
Nov 2, 2018 3:40:41 PM >> document/documentHighlight
Nov 2, 2018 3:40:41 PM >> document/hover
Nov 2, 2018 3:40:46 PM >> workspace/executeCommand java.edit.organizeImports
Nov 2, 2018 3:40:46 PM Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
null
java.lang.NullPointerException
	at org.eclipse.jdt.ls.core.internal.JavaClientConnection.applyWorkspaceEdit(JavaClientConnection.java:181)
	at org.eclipse.jdt.ls.core.internal.JDTDelegateCommandHandler.executeCommand(JDTDelegateCommandHandler.java:34)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:141)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:433)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$26(JDTLanguageServer.java:764)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

lsp-mode version: 20181031.1905
lsp-java version: 20181025.1822

**Comment by yyoncho** [comment]
Closing due to inactivity. Please reopen after providing the requested in information https://github.com/emacs-lsp/lsp-java/issues/73#issuecomment-435304761
