### ISSUE TITLE
Can't download Gradle behind proxy

### ISSUE THREAD

**Issue by zijianyue** [emacs-lsp/lsp-java#94]
**Describe the bug**
Below is the message:

2019-1-22 15:14:24 Could not load Gradle version information
Cannot download published Gradle versions.
org.gradle.api.UncheckedIOException: Cannot download published Gradle versions.

	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:164)

	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.tryToDownloadAndCacheVersions(PublishedGradleVersions.java:148)

	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.create(PublishedGradleVersions.java:108)

	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersionsWrapper$LoadVersionsJob.run(PublishedGradleVersionsWrapper.java:62)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)

	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)

	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)

	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)

	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)

	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)

	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)

	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)

	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)

	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)

	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)

	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)

	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)

	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)

	at org.eclipse.buildship.core.internal.util.gradle.PublishedGradleVersions.downloadVersionInformation(PublishedGradleVersions.java:161)

	... 4 more

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)

	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)

	at sun.security.validator.Validator.validate(Validator.java:262)

	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)

	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)

	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)

	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)

	... 17 more

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)

	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)

	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)

	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)

	... 23 more

**Note**
Before logging the bug please make sure that the issue is reproducible with latest melpa packages and it is reproducible with the clean config(the config from the getting started page.

**To Reproduce**
{populate}

**Expected behavior**
{populate}

**Screenshots**

**Logs**
Please include the debug stack trace (if there is an error) and the content of Messages buffer with `lsp-print-io` set to t in case the bug is related to client->server communication.

**Comment by yyoncho** [comment]
I don't think that there is anything that I can do on lsp-java side. I would recommend you to reinstall jdk and/or download other version of the jdk (I recommend oracle-jdk-8). Have you tested the same code without proxy? If new jdk does not fix the issue I would recommend opening a new issue in Eclipse JDT LS repo.
