### ISSUE TITLE
Spring Initializr failed to discover tests

### ISSUE THREAD

**Issue by SebastianCallh** [emacs-lsp/lsp-java#97]
**Describe the bug**
After installing `lsp-java` as described in the README and initializing a project with `lsp-java-spring-initializr` with either Maven or Gradle for spring boot 2.1.2,  both `dap-java-run-test-classes` and `dap-java-run-test-classes` fails with the stack trace seen in the Logs section. It seems similar to [this](https://github.com/yyoncho/dap-mode/issues/179) issue, however the name of the test file is the default generated `DemoApplicationTests` so it is not quite the same.

**To Reproduce**
- Make a clean install according to README 
- Run `lsp-java-spring-initializr` with either Maven or Gradle for spring boot 2.1.2,
- Run either `dap-java-run-test-classes` or `dap-java-run-test-classes`

**Expected behavior**
Tests are run without warning or stack trace.

**Screenshots**
No screenshots attached.

**Logs**
java -jar c:/Users/sebas/.emacs.d/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar -cp $JUNIT_CLASS_PATH -c com.seba.aoc.DemoApplication
Feb 08, 2019 5:07:52 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: com.seba.aoc.DemoApplication
	at org.junit.platform.engine.discovery.ClassSelector.lambda$getJavaClass$0(ClassSelector.java:73)
	at java.util.Optional.orElseThrow(Unknown Source)
	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:72)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.junit.vintage.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:29)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.collectTestClasses(VintageDiscoverer.java:64)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:51)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:61)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:132)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:119)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:92)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
	at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:84)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:74)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
	at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)

**Comment by yyoncho** [comment]
My guess is that the issue is caused the fact that the auto-build setting does not work. Also, dap-java has a bug(it should trigger build before any operation). Can you do lsp-java-build-project before running the application and report back?

**Comment by SebastianCallh** [comment]
Thank you for your quick response. Unfortunately the error persists after `lsp-java-build-project`. I should also mention that both build and test work with Maven.

**Comment by yyoncho** [comment]
> java -jar c:/Users/sebas/.emacs.d/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar -cp $JUNIT_CLASS_PATH -c **com.seba.aoc.DemoApplication**

Just noticed that you are starting the test from DemoApplication, you should do that from DemoApplicationTests.java .

**Comment by SebastianCallh** [comment]
I have tried to do it from both files. Here is the stack trace from when I run it from DemoApplicationTests

java -jar c:/Users/sebas/.emacs.d/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar -cp $JUNIT_CLASS_PATH -c com.seba.aoc.DemoApplicationTest
Feb 08, 2019 6:10:16 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
org.junit.platform.commons.util.PreconditionViolationException: Could not load class with name: com.seba.aoc.DemoApplicationTest
	at org.junit.platform.engine.discovery.ClassSelector.lambda$getJavaClass$0(ClassSelector.java:73)
	at java.util.Optional.orElseThrow(Unknown Source)
	at org.junit.platform.engine.discovery.ClassSelector.getJavaClass(ClassSelector.java:72)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.junit.vintage.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:29)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.collectTestClasses(VintageDiscoverer.java:64)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:51)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:61)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:132)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:119)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:92)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
	at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
	at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:84)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:74)
	at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:47)
	at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:39)

[36m.[0m
[36m'--[0m [36mJUnit Jupiter[0m [32m[OK][0m

Test run finished after 19 ms
[         1 containers found      ]
[         0 containers skipped    ]
[         1 containers started    ]
[         0 containers aborted    ]
[         1 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]


Compilation finished at Fri Feb  8 18:10:16

**Comment by yyoncho** [comment]
> java -jar c:/Users/sebas/.emacs.d/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar -cp $JUNIT_CLASS_PATH -c **com.seba.aoc.DemoApplicationTest**

Hm, on my side the class is called  DemoApplicationTests.java, is it really DemoApplicationTest.java on your side?

If you have gitter, we may move the conversation there, since it is a bit quicker.
